/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.zaproxy.zap.extension.jiraIssueCreater;

import com.sun.jersey.core.util.Base64;
import org.json.JSONArray;
import org.json.JSONObject;
import org.parosproxy.paros.Constant;
import org.parosproxy.paros.view.View;


import javax.naming.AuthenticationException;
import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.util.Properties;

/**
 * @author kasun
 */
public class ExportToJira extends JFrame {

    /**
     * Creates new form ExportToJira
     */
    public ExportToJira() {
        initComponents();
        this.listJiraProjects();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cbProjectKeys = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        tbProjectLocation = new javax.swing.JTextField();
        btnChooseReport = new javax.swing.JButton();
        btnExport = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Project Key");

        cbProjectKeys.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbProjectKeysActionPerformed(evt);
            }
        });

        jLabel5.setText("Choose Report ");
        jLabel5.setFocusCycleRoot(true);

        tbProjectLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbProjectLocationActionPerformed(evt);
            }
        });

        btnChooseReport.setText("Choose");
        btnChooseReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChooseReportActionPerformed(evt);
            }
        });

        btnExport.setText("Export");
        btnExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5))
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnExport, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cbProjectKeys, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(tbProjectLocation)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnChooseReport)))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbProjectKeys, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tbProjectLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnChooseReport))
                    .addComponent(jLabel5))
                .addGap(122, 122, 122)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExport)
                    .addComponent(btnCancel))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    //    private static String BASE_URL = "http://localhost:8081";
//    String auth = new String(Base64.encode("kmbkck1@gmail.com:kmbkck211"));
    static String filePath = "";

    private void listJiraProjects(){
        try {

            Properties prop=new Properties();
            InputStream input=new FileInputStream(Constant.getZapHome()+"/cred.properties");
            prop.load(input);

            if (!(prop.getProperty("jiraUrl").equals("")) && !(prop.getProperty("jiraUsername").equals("")) && !(prop.getProperty("jiraPass").equals(""))) {

                //Get Projects
                String BASE_URL = prop.getProperty("jiraUrl");
                String auth = new String(Base64.encode(prop.getProperty("jiraUsername") + ":" + prop.getProperty("jiraPass")));

//                System.out.println(BASE_URL+"----------"+auth);
                String projects = JiraRestClient.invokeGetMethod(auth, BASE_URL + "/rest/api/2/project"); // rest call to get the list of projects
//                System.out.println(projects);
                JSONArray projectArray = new JSONArray(projects);
                for (int i = 0; i < projectArray.length(); i++) {
                    JSONObject proj = projectArray.getJSONObject(i);
//                System.out.println("Key:" + proj.getString("key") + ", Name:" + proj.getString("name"));
                    cbProjectKeys.addItem(proj.getString("key") + " - " + proj.getString("name"));// add the projects to the combobox
                }
//            } else if (tbPassword.getPassword().toString().equals("")) {
//                View.getSingleton().showMessageDialog("Enter Password");
//            } else if (tbJiraUrl.getText().equals("")) {
//                View.getSingleton().showMessageDialog("Enter Jira Home URL");
            }else{
                //TODO add other validations
                return;
            }
        } catch (AuthenticationException e) {
//            e.printStackTrace();
            View.getSingleton().showMessageDialog(e.getMessage());
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    private void btnChooseReportActionPerformed(java.awt.event.ActionEvent evt) {//Choose .xml or .html file
        JFileChooser reportLocation = new JFileChooser();
        FileNameExtensionFilter xmlfilter = new FileNameExtensionFilter("XML report", "xml");
        FileNameExtensionFilter htmlfilter = new FileNameExtensionFilter("HTML report", "html");
        reportLocation.setFileFilter(xmlfilter);
        reportLocation.setFileFilter(htmlfilter);

        int returnValue = reportLocation.showOpenDialog(reportLocation);

        if (returnValue == JFileChooser.APPROVE_OPTION) {
            tbProjectLocation.setText(reportLocation.getSelectedFile().getName());
            filePath = reportLocation.getSelectedFile().getAbsolutePath();
        }


    }

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {// dispose the current screen
        dispose();
    }
    

    private void cbProjectKeysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbProjectKeysActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbProjectKeysActionPerformed

    private void tbProjectLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbProjectLocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbProjectLocationActionPerformed

    private void btnExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportActionPerformed
        // TODO add your handling code here:

//        String auth = new String(Base64.encode(tbUserName.getText() + ":" + tbPassword.getText()));
//        String BASE_URL = tbJiraUrl.getText();
//        String[] project_key = cbProjectKeys.getSelectedItem().toString().split(" ");
//        System.out.println(project_key[0]);
//        String issueList[];
//        JiraRestClient jira = new JiraRestClient();
//        int issueCount;
//        String issue;
//
//
//        try {
//
//            if (filePath.contains(".xml")) {
//
//                //to parse xml
//
//                XmlDomParser xmlParser = new XmlDomParser();
//                issueList = xmlParser.parseXmlDoc(project_key[0], filePath);
//
//
//                issueCount = Integer.parseInt(issueList[999]);
//                for (int i = 0; i < issueCount; i++) { //create Issues in jira
//                    System.out.println("Issuelist " + i + issueList[i]);
//                    issue = jira.invokePostMethod(auth, BASE_URL + "/rest/api/2/issue", issueList[i]);
//                    filePath="";
//                    System.out.println(issue);
////                    View.getSingleton().showMessageDialog("Done creting issues!!");
//                }
//
//            } else if (filePath.contains(".html")) {
//
//                HtmlParser htmlParser = new HtmlParser();
//                issueList = htmlParser.CreateIssueList(htmlParser.ReadHtmldoc(filePath), project_key[0]);
//
//
//                issueCount = Integer.parseInt(issueList[999]);
//                for (int i = 0; i < issueCount; i++) { //create Issues in jira
//                    System.out.println("Issuelist " + i + issueList[i]);
//                    issue = jira.invokePostMethod(auth, BASE_URL + "/rest/api/2/issue", issueList[i]);
//                    filePath="";
//                    System.out.println(issue);
////                    View.getSingleton().showMessageDialog("Done creting issues!!");
//
//
//                }
//            }else if(filePath.equals("")){
//                View.getSingleton().showMessageDialog("Please Select a report file !!");
//            }
//            }catch(AuthenticationException e1){
//                e1.printStackTrace();
//            }
//            finally{
//            View.getSingleton().showMessageDialog("Done creting issues!!");
//                this.dispose();
//            }
        Properties prop=new Properties();
        InputStream input= null;
        try {
            input = new FileInputStream(Constant.getZapHome()+"/cred.properties");
            prop.load(input);
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        }



        }//GEN-LAST:event_btnExportActionPerformed



        /**
         * @param args the command line arguments
         */

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExportToJira.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExportToJira.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExportToJira.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExportToJira.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExportToJira().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnChooseReport;
    private javax.swing.JButton btnExport;
    private javax.swing.JComboBox cbProjectKeys;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField tbProjectLocation;
    // End of variables declaration//GEN-END:variables
}
