/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.zaproxy.zap.extension.jiraIssueCreater;

import com.sun.jersey.core.util.Base64;
import org.json.JSONArray;
import org.json.JSONObject;
import org.parosproxy.paros.view.View;


import javax.naming.AuthenticationException;
import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 * @author kasun
 */
public class ExportToJira extends JFrame {

    /**
     * Creates new form ExportToJira
     */
    public ExportToJira() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new JLabel();
        cbProjectKeys = new JComboBox();
        jLabel2 = new JLabel();
        tbJiraUrl = new JTextField();
        jLabel3 = new JLabel();
        tbUserName = new JTextField();
        jLabel4 = new JLabel();
        tbPassword = new JPasswordField();
        jLabel5 = new JLabel();
        tbProjectLocation = new JTextField();
        btnChooseReport = new JButton();
        btnExport = new JButton();
        btnCancel = new JButton();
        btnLogin = new JButton();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Project Key");

        cbProjectKeys.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbProjectKeysActionPerformed(evt);
            }
        });

        jLabel2.setText("Jira Home URL");

        tbJiraUrl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbJiraUrlActionPerformed(evt);
            }
        });

        jLabel3.setText("Username");

        tbUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbUserNameActionPerformed(evt);
            }
        });

        jLabel4.setText("Password");

        tbPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbPasswordActionPerformed(evt);
            }
        });

        jLabel5.setText("Choose Report ");
        jLabel5.setFocusCycleRoot(true);

        tbProjectLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbProjectLocationActionPerformed(evt);
            }
        });

        btnChooseReport.setText("Choose");
        btnChooseReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChooseReportActionPerformed(evt);
            }
        });

        btnExport.setText("Export");
        btnExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnLogin.setText("LogIn");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel5))
                                .addGap(81, 81, 81)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnExport, GroupLayout.PREFERRED_SIZE, 124, GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                                                .addComponent(btnCancel, GroupLayout.PREFERRED_SIZE, 118, GroupLayout.PREFERRED_SIZE))
                                        .addComponent(cbProjectKeys, 0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(tbProjectLocation)
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btnChooseReport))
                                        .addComponent(tbJiraUrl)
                                        .addComponent(tbUserName)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(tbPassword, GroupLayout.PREFERRED_SIZE, 205, GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btnLogin, GroupLayout.PREFERRED_SIZE, 66, GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(105, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(tbJiraUrl, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(tbUserName, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4)
                                        .addComponent(tbPassword)
                                        .addComponent(btnLogin))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(cbProjectKeys, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5)
                                        .addComponent(tbProjectLocation, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnChooseReport))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnExport)
                                        .addComponent(btnCancel))
                                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    //    private static String BASE_URL = "http://localhost:8081";
//    String auth = new String(Base64.encode("kmbkck1@gmail.com:kmbkck211"));
    static String filePath = "";


    private void tbJiraUrlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbJiraUrlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbJiraUrlActionPerformed


    private void btnChooseReportActionPerformed(java.awt.event.ActionEvent evt) {//Choose .xml or .html file
        JFileChooser reportLocation = new JFileChooser();
        FileNameExtensionFilter xmlfilter = new FileNameExtensionFilter("XML report", "xml");
        FileNameExtensionFilter htmlfilter = new FileNameExtensionFilter("HTML report", "html");
        reportLocation.setFileFilter(xmlfilter);
        reportLocation.setFileFilter(htmlfilter);

        int returnValue = reportLocation.showOpenDialog(reportLocation);

        if (returnValue == JFileChooser.APPROVE_OPTION) {
            tbProjectLocation.setText(reportLocation.getSelectedFile().getName());
            filePath = reportLocation.getSelectedFile().getAbsolutePath();
        }


    }

    private void tbUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbUserNameActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {// dispose the current screen
        dispose();
    }

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {// login with jira credentials

        try {

            if (!(tbPassword.getPassword().toString().equals("")) && !(tbJiraUrl.getText().equals(""))) {

                //Get Projects
                String BASE_URL = tbJiraUrl.getText();
                String auth = new String(Base64.encode(tbUserName.getText() + ":" + tbPassword.getText()));

//                System.out.println(BASE_URL+"----------"+auth);
                String projects = JiraRestClient.invokeGetMethod(auth, BASE_URL + "/rest/api/2/project"); // rest call to get the list of projects
//                System.out.println(projects);
                JSONArray projectArray = new JSONArray(projects);
                for (int i = 0; i < projectArray.length(); i++) {
                    JSONObject proj = projectArray.getJSONObject(i);
//                System.out.println("Key:" + proj.getString("key") + ", Name:" + proj.getString("name"));
                    cbProjectKeys.addItem(proj.getString("key") + " - " + proj.getString("name"));// add the projects to the combobox
                }
            } else if (tbPassword.getPassword().toString().equals("")) {
                View.getSingleton().showMessageDialog("Enter Password");
            } else if (tbJiraUrl.getText().equals("")) {
                View.getSingleton().showMessageDialog("Enter Jira Home URL");
            }else{
                //TODO add other validations
                return;
            }
        } catch (AuthenticationException e) {
//            e.printStackTrace();
            View.getSingleton().showMessageDialog(e.getMessage());
        }

    }//GEN-LAST:event_btnLoginActionPerformed

    private void tbPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbPasswordActionPerformed

    private void cbProjectKeysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbProjectKeysActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbProjectKeysActionPerformed

    private void tbProjectLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbProjectLocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbProjectLocationActionPerformed

    private void btnExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportActionPerformed
        // TODO add your handling code here:

        String auth = new String(Base64.encode(tbUserName.getText() + ":" + tbPassword.getText()));
        String BASE_URL = tbJiraUrl.getText();
        String[] project_key = cbProjectKeys.getSelectedItem().toString().split(" ");
        System.out.println(project_key[0]);
        String issueList[];
        JiraRestClient jira = new JiraRestClient();
        int issueCount;
        String issue;


        try {

            if (filePath.contains(".xml")) {

                //to parse xml

                XmlDomParser xmlParser = new XmlDomParser();
                issueList = xmlParser.parseXmlDoc(project_key[0], filePath);


                issueCount = Integer.parseInt(issueList[999]);
                for (int i = 0; i < issueCount; i++) { //create Issues in jira
                    System.out.println("Issuelist " + i + issueList[i]);
                    issue = jira.invokePostMethod(auth, BASE_URL + "/rest/api/2/issue", issueList[i]);
                    filePath="";
                    System.out.println(issue);
//                    View.getSingleton().showMessageDialog("Done creting issues!!");
                }

            } else if (filePath.contains(".html")) {

                HtmlParser htmlParser = new HtmlParser();
                issueList = htmlParser.CreateIssueList(htmlParser.ReadHtmldoc(filePath), project_key[0]);


                issueCount = Integer.parseInt(issueList[999]);
                for (int i = 0; i < issueCount; i++) { //create Issues in jira
                    System.out.println("Issuelist " + i + issueList[i]);
                    issue = jira.invokePostMethod(auth, BASE_URL + "/rest/api/2/issue", issueList[i]);
                    filePath="";
                    System.out.println(issue);
//                    View.getSingleton().showMessageDialog("Done creting issues!!");


                }
            }else if(filePath.equals("")){
                View.getSingleton().showMessageDialog("Please Select a report file !!");
            }
            }catch(AuthenticationException e1){
                e1.printStackTrace();
            }
            finally{
            View.getSingleton().showMessageDialog("Done creting issues!!");
                this.dispose();
            }


        }//GEN-LAST:event_btnExportActionPerformed

        /**
         * @param args the command line arguments
         */

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExportToJira.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExportToJira.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExportToJira.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExportToJira.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExportToJira().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton btnCancel;
    private JButton btnChooseReport;
    private JButton btnExport;
    private JButton btnLogin;
    private JComboBox cbProjectKeys;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JLabel jLabel5;
    private JTextField tbJiraUrl;
    private JPasswordField tbPassword;
    private JTextField tbProjectLocation;
    private JTextField tbUserName;
    // End of variables declaration//GEN-END:variables
}
